FROM mcr.microsoft.com/devcontainers/base:ubuntu
# Install packages needed for working with latex
RUN apt-get update && apt-get install -y texlive-science texlive-latex-extra texlive-extra-utils latexmk texlive-publishers texlive-science texlive-fonts-extra